apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-apps
spec:
  replicas: 5
  selector:
    matchLabels:
      app: my-apps
  template:
    metadata:
      labels:
        app: my-apps
    spec:
      containers:
        - name: waad
          image: waadhouij/microapp # Remplacez par le nom de votre image Docker
          ports:
           - containerPort: 3000  # Port sur lequel votre application écoute dans le conteneur
