apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 3  # Définir le nombre de répliques souhaitées
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest  # Utiliser l'image la plus récente de Nginx
        ports:
        - containerPort: 80  # Exposer le port 80 du conteneur
