apiVersion: v1
kind: Service
metadata:
  name: my-app-nodeport-service
spec:
  type: NodePort
  selector:
    app: my-app  # Cette étiquette doit correspondre à celle définie dans votre deployment.yaml
  ports:
    - protocol: TCP
      port: 80  # Port que le service expose
      targetPort: 3000  # Port sur lequel votre application écoute dans le conteneur
      nodePort: 31000  # Port NodePort spécifique pour Minikube, ajustez-le selon vos besoins
